### ISSUE TITLE
Rails 7 - Unable to set Lowkiq.workers in initializer

### ISSUE THREAD

**Issue by geophilusd** [bia-technologies/lowkiq#25]
I created a new rails 7 application, added the lowkiq gem and configured the initializer with 1 worker. When I tried starting the application, it threw `uninitialized constant TestWorker`.

Version
```
Ruby 3.1.2
Rails 7.0.3
```

I have this in my initializer
```
Lowkiq.workers = [TestWorker]
```
and i have defined TestWorker in `/app/workers/test_worker.rb`
```
class TestWorker
  extend Lowkiq::Worker

  def self.perform
  end
end
```

I got these logs during app startup
```
=> Booting Puma
=> Rails 7.0.3 application starting in development 
=> Run `bin/rails server --help` for more startup options
Exiting
/Users/geophilusd/sample_apps/sample7/config/initializers/lowkiq.rb:11:in `<main>': uninitialized constant TestWorker (NameError)

  TestWorker
  ^^^^^^^^^^
  from /Users/geophilusd/.rvm/gems/ruby-3.1.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
  from /Users/geophilusd/.rvm/gems/ruby-3.1.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
  from /Users/geophilusd/.rvm/gems/ruby-3.1.2/gems/railties-7.0.3/lib/rails/engine.rb:667:in `block in load_config_initializer'
  from /Users/geophilusd/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.3/lib/active_support/notifications.rb:208:in `instrument'
  from /Users/geophilusd/.rvm/gems/ruby-3.1.2/gems/railties-7.0.3/lib/rails/engine.rb:666:in `load_config_initializer'
  from /Users/geophilusd/.rvm/gems/ruby-3.1.2/gems/railties-7.0.3/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
  from /Users/geophilusd/.rvm/gems/ruby-3.1.2/gems/railties-7.0.3/lib/rails/engine.rb:619:in `each'
  from /Users/geophilusd/.rvm/gems/ruby-3.1.2/gems/railties-7.0.3/lib/rails/engine.rb:619:in `block in <class:Engine>'
  from /Users/geophilusd/.rvm/gems/ruby-3.1.2/gems/railties-7.0.3/lib/rails/initializable.rb:32:in `instance_exec'
  from /Users/geophilusd/.rvm/gems/ruby-3.1.2/gems/railties-7.0.3/lib/rails/initializable.rb:32:in `run'
  from /Users/geophilusd/.rvm/gems/ruby-3.1.2/gems/railties-7.0.3/lib/rails/initializable.rb:61:in `block in run_initializers'
  from /Users/geophilusd/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
  from /Users/geophilusd/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  from /Users/geophilusd/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  from /Users/geophilusd/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
  from /Users/geophilusd/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  from /Users/geophilusd/.rvm/gems/ruby-3.1.2/gems/railties-7.0.3/lib/rails/initializable.rb:50:in `each'
  from /Users/geophilusd/.rvm/gems/ruby-3.1.2/gems/railties-7.0.3/lib/rails/initializable.rb:50:in `tsort_each_child'
  from /Users/geophilusd/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:415:in `call'
  from /Users/geophilusd/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:415:in `each_strongly_connected_component_from'
  from /Users/geophilusd/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
  from /Users/geophilusd/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each'
  from /Users/geophilusd/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `call'
  from /Users/geophilusd/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
  from /Users/geophilusd/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
  from /Users/geophilusd/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
  from /Users/geophilusd/.rvm/gems/ruby-3.1.2/gems/railties-7.0.3/lib/rails/initializable.rb:60:in `run_initializers'
  from /Users/geophilusd/.rvm/gems/ruby-3.1.2/gems/railties-7.0.3/lib/rails/application.rb:372:in `initialize!'
  from /Users/geophilusd/sample_apps/sample7/config/environment.rb:5:in `<main>'
  from config.ru:3:in `require_relative'
  from config.ru:3:in `block in <main>'
```

I made the following change to `initializers/lowkiq.rb` and server started properly. Ref: https://github.com/bia-technologies/lowkiq/pull/22/files
```
Dir["#{Rails.root}/app/workers/*.rb"].each { |file| require_dependency file }
```

**Comment by geophilusd** [comment]
Fixed it by wrapping it like this:
```
Rails.application.config.to_prepare do
  Lowkiq.workers = [
    TestWorker
  ]
end
```

@darkleaf Can we add this to the readme? or do you have any other suggestions for fixing this?

**Comment by darkleaf** [comment]
Sure 👍 . Please send PR.
Please add notice that this option is only for rails 7.
